Rails.application.routes.draw do
  get 'message/show'
  get 'user/show'
  get 'user/edit' => 'user#edit'
  get 'user/update' => 'user#update'
  post 'user/update' => 'user#update'
  get 'dashboad/show'
  get 'mecha' => 'mecha#show'
  get 'mecha/message' => 'mecha#message'
  post 'mecha' => 'mecha#show'
  get 'stuff/show' => 'stuff#show'
  post 'stuff/show' => 'stuff#show'
  get 'message' => 'message#show'
  post 'message' => 'message#show'
  get 'message/edit' => 'message#edit'
  get 'message/new' => 'message#new'
  get 'message/edit' => 'message#edit'
  get 'message/update' => 'message#update'
  post 'message/update' => 'message#update'
  delete 'message/delete' => 'message#delete'
  get 'member' => 'member#show'
  post 'member' => 'member#show'
  get 'member/show' => 'member#show'
  post 'member/show' => 'member#show'
  get 'member/show4crud' => 'member#show4crud'
  post 'member/edit' => 'member#edit'
  get 'member/edit' => 'member#edit'
  get 'member/new' => 'member#new'
  post 'member/new' => 'member#new'
  get 'member/update' => 'member#update'
  post 'member/update' => 'member#update'
  delete 'member/delete' => 'member#delete'
  get 'member/attend' => 'member#attend'
  post 'member/attend' => 'member#attend'
  get 'member/updstatus' => 'member#updstatus'
  get 'member/ninzu' => 'member#ninzu'
  get 'member/leave' => 'member#leave'
  post 'dashboad/show' => 'dashboad#show'
  root 'joinus#show'
  get 'joinus' => 'joinus#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
